version: '3.9'
services:
  php:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: testclearphp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../:/var/www/html
      - ./log/php-error.log:/var/log/php/error.log
    networks:
      - testclearphp_network
    depends_on:
      - db

  nginx:
    container_name: testclearphp-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - testclearphp_network
    depends_on:
      - php

  db:
    container_name: testclearphp-db
    image: mysql:latest
    env_file: ../.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - testclearphp_network
    ports:
      - "3307:3306"

networks:
  testclearphp_network:
    driver: bridge

volumes:
  mysqldata:
